name: first workflow
on: workflow_dispatch
jobs:
   print-github:
      runs-on: ubuntu-latest
      env: 
        CUSTOM_VAR: "Hello World"
      steps:
         - name: print github
           run: |
            echo "Repository name: $GITHUB_REPOSITORY"
            echo "Branch or tag reference: $GITHUB_REF"
            echo "Commit SHA: $GITHUB_SHA"
         - name: Step Two
           run: |
            echo "Custom Variable: $CUSTOM_VAR"
